
[global]
dimension = 3
dt = 0.007911
particles_per_cell = 4
shapefunctions = "cubic" #TODO
output_directory = "output"
total_steps = 10000
output_steps = 100 #frequency
output_start = 0
cell_size_ratio = 40.0

[nodes]
node_start = [0.0, 0.0]
node_end = [4.0,1.0]
node_spacing = 0.05
output_formats = ["vtk", "csv"] #TODO

[particles]
output_formats = ["vtk", "csv"] #TODO

[material]
density=2500
E=1e7
pois=0.3
I0=0.278
mu_s=0.3019
mu_2=0.4435
rho_c=1485
particle_diameter=0.005
particle_density=2450

[solver]
alpha = 0.95

[boundaryconditions]
gravity = [0.0,0.0, -0.1]
axis0_mode=[1,1,0]
axis1_mode=[1,1,1]
# axis0_mode=[1,1,0]
# axis1_mode=[1,1,1]


[project]
domain_file = "domain.stl"
material_file = "material.stl"
scoop_file = "scoop.stl"
scoop_motion_file = "scoop.chan"

[postprocess]
movie_file = "plots/scoop.mp4"