[global]
timestep = 0.001

num_steps = 1000
output_steps = 25

[material]
E = 1E5
pois = 0.2
density = 1000
cohesion = 0.1
friction_angle = 0.3
dilatancy_angle = 0.2
H = 2e4

[uniaxial]
deps_xx = 0.1
output_directory = "./output/uniaxial/"


[simpleshear]
deps_xy = 0.1
output_directory = "./output/simpleshear/"
