[global]
time = 1
timestep = 0.000001

num_steps = 1000
output_steps = 25

[material]
E = 1E5
pois = 0.2
density = 1000
yield_stress = 1000
H = 2e4

[uniaxial]
deps_xx = 0.1
output_directory = "./output/uniaxial/"


[simpleshear]
deps_xy = 0.1
output_directory = "./output/simpleshear/"