[global]
timestep = 0.001

num_steps = 10000
output_steps = 400

[material]
E = 1E6
pois = 0.2
density = 1000


[uniaxial]
deps_xx = 0.1
output_directory = "./output/uniaxial/"


[simpleshear]
deps_xy = 0.1
output_directory = "./output/simpleshear/"