[global]
dimension = 3
particles_per_cell = 2
shapefunctions = "cubic"    #TODO
output_directory = "output"
total_steps = 20000
output_steps = 200          #frequency
output_start = 0
cell_size_ratio = 30.0

[nodes]
node_start = [0.0, 0.0]
node_end = [4.0, 1.0]
node_spacing = 0.05
output_formats = ["vtk", "csv"] #TODO

[particles]
output_formats = ["vtk", "csv"] #TODO

[material]
density = 997.5
bulk_modulus = 2e6
mu = 0.001

[solver]
alpha = 0.95

[boundaryconditions]
gravity = [0.0, 0.0, -9.8]
axis0_mode = [0, 0, 1]
axis1_mode = [0, 0, 1]
# axis0_mode=[1,1,0]
# axis1_mode=[1,1,1]


[project]
domain_file = "domain.stl"
material_file = "material.stl"

[postprocess]
movie_file = "plots/water.gif"
