
[global]
dimension = 2
dt = 0.001
particles_per_cell = 4
shapefunctions = "cubic" #TODO
output_directory = "output"
total_steps = 4800
output_steps = 100 #frequecy
output_start = 0

[nodes]
node_start = [-0.2, -0.2]
node_end = [1.2,1.2]
node_spacing = 0.05
output_formats = ["vtk", "csv"] #TODO

[particles]
output_formats = ["vtk", "csv"] #TODO
# Project specific
circle1_center = [0.2, 0.2]
circle2_center = [0.8, 0.8]
circle_radius = 0.2
initial_velocity_mag = 1.0

[material]
density = 1000
E = 1000
pois =0.3

[solver]
alpha = 0.99

[boundaryconditions]
gravity = [0.0, -0.1]
axis0_friction=[1.0, 1.0]
axis1_friction=[1.0, 1.0]

[postprocess]
movie_file = "plots/disc_impact.gif"