[global]
time = 1.0
timestep = 0.0001
output_steps = 500
output_dir = "./output/"
plot_dir = "./plots/"

[material]
density = 1000
volume = 1000

[von_mises]
E = 1E6
pois = 0.2
yield_stress = 10000
H = 0

[modified_cam_clay]
density = 1000
E = 1E6
pois = 0.2
M = 0.8
lam = 0.05
kap = 0.1
Vs = 1400
Pt = 0
beta = 0.1


[mixed_control]
tolerance = 1e-6
is_finite = false