[global]
time = 1.0
timestep = 0.0001
output_steps = 100
output_dir = "./output/modified_cam_clay/"

[mixed_control]
tolerance = 1e-6
is_finite_strain = false

[white_lists]
model_names = ["dense","loose"]
benchmark_names = [
    "simple_shear",
    "triaxial"
    ]
plot_names = ["q_p","stress_vs_steps","stress_vs_strain","shear_volume_strain"]

[[plot]]
name = "q_p"
type = "q_p"

[[plot]]
name = "stress_vs_steps"
type = "stress_vs_steps"

[[plot]]
name = "stress_vs_strain"
type = "stress_vs_strain"

[[plot]]
name = "shear_volume_strain"
type = "shear_volume_strain"

[[models]]
type = "modified_cam_clay"
name = "dense" 
prestress = [
    [-5000.0,    0.0, 0.0    ],
    [0.0    ,  -5000.0, 0.0    ],
    [0.0,           0, -5000.0]
]
density = 1000
volume = 1000
Pc0 = 5000
E = 1E6
pois = 0.2
M = 1.05
lam = 0.130
kap = 0.033
Vs = 900
Pt = 0.0
beta = 1.0


[[models]]
type = "modified_cam_clay"
name = "loose" 
prestress = [
    [-5000.0,    0.0, 0.0    ],
    [0.0    ,  -5000.0, 0.0    ],
    [0.0,           0, -5000.0]
]
density = 1000
volume = 10000
Pc0 = 5000
E = 1E6
pois = 0.2
M = 1.05
lam = 0.130
kap = 0.033
Vs = 900
Pt = 0.0
beta = 1.0

[[benchmarks]]
name = "simple_shear"
[[benchmarks.run]]
target_strain = [
[0.0, -0.12, 0.0],
[0.0, 0.0, 0.0],
[0.0, 0.0, 0.0] 
]
target_stress = [
    [0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0]
    ]
is_stress_control = [
    [false, false, false],
    [false, false, false],
    [false, false, false]
    ]

[[benchmarks]]
name = "triaxial"
[[benchmarks.run]]
target_strain = [
[-0.12, 0.0, 0.0],
[0.0, 0.0, 0.0],
[0.0, 0.0, 0.0] 
]
target_stress = [
    [0.0, 0.0, 0.0],
    [0.0, -5000.0, 0.0],
    [0.0, 0.0, -5000.0]
    ]
is_stress_control = [
    [false, false, false],
    [false, true, false],
    [false, false, true]
    ]