name: Build Test CPU
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.head_ref || github.run_id }}

jobs:
  build:
    strategy:
      matrix:
          os: [ubuntu-22.04]
          python-version: ["3.8","3.9","3.11","3.12"]
#           poetry-version: ["1.0", "1.1.15"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "true"
          path: project
      
      - name: change working directory
        run: |
          cd project
      
      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive
          echo "Installing dependencies . . ."
          sudo apt-get -y update --no-install-recommends 
          sudo apt-get -y install --no-install-recommends build-essential curl git vtk9 libvtk9-dev libthrust-dev cmake python-is-python3
          sudo apt-get autoremove -y
          sudo apt-get clean -y
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          ls -la
        

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Run image
        uses: abatilo/actions-poetry@v2
#         with:
#           poetry-version: ${{ matrix.poetry-version }}
          
      - name: Install Python package dependencies
        run: |
          poetry --version
          rm -f poetry.lock
          poetry lock --no-update
          poetry install --without plot
      
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
      
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ../ -DBUILD_CUDA=off
          make -j4
      
      - name: Test
        run: |
          tests/tests
