name: Build
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag: 
        type: string
  
concurrency:
  group: ${{ github.head_ref || github.run_id }}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python-version: ["3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive
          echo "Installing dependencies . . ."
          sudo apt-get -y update --no-install-recommends 
          sudo apt-get -y install --no-install-recommends build-essential curl git vtk9 libvtk9-dev libthrust-dev cmake python-is-python3
          sudo apt-get autoremove -y
          sudo apt-get clean -y

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2

      - name: Install Python package dependencies
        run: |
          poetry --version
          rm -f poetry.lock
          poetry lock --no-update
          poetry install --without plot

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ../ -DBUILD_CUDA=off
          make -j4
