name: build-cpu
description: 'build-cpu version of code'
inputs:
  os:  # id of input
    description: 'Operating system'
    required: true
    default: ubuntu-22.04
  python-version:
    description: 'Python version'
    required: true
    default: 3.11
    
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        DEBIAN_FRONTEND=noninteractive
        echo "Installing dependencies . . ."
        sudo apt-get -y update --no-install-recommends 
        sudo apt-get -y install --no-install-recommends build-essential curl git vtk9 libvtk9-dev libthrust-dev cmake python-is-python3
        sudo apt-get autoremove -y
        sudo apt-get clean -y

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Run image
      uses: abatilo/actions-poetry@v2

    - name: Install Python package dependencies
      run: |
        poetry --version
        rm -f poetry.lock
        poetry lock --no-update
        poetry install --without plot

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ../ -DBUILD_CUDA=off
        make -j4
