name: Build Test CPU
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.run_id }}

jobs:
  build:
    strategy:
      matrix:
          os: [ubuntu-22.04]
          python-version: ["3.11"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          submodules: "recursive"
    - name: CI composite build
      uses: TUSAIL/PyroclastMPM/.github/workflows/ci-build-staging.yml@main
      with:
        os:  ${{ matrix.os }}
        python-version:  ${{ matrix.python-version }}

    - name: Trunk Check
      uses: trunk-io/trunk-action@v1
      
    - name: Test
      run: ./build/tests/tests
